name: Publish
on: [push]
jobs:
  # This workflow contains a single job called "SFTP-Deploy-Action"
  CodeCheckout:
    #name: Clone files on amitchandi.com
    runs-on: self-hosted
    steps:
        - uses: actions/checkout@v3
          with:
            # Fetch all history for all tags and branches
            fetch-depth: 0
            # Checkout a specific branch
            ref: main
  PullProject:
    needs: CodeCheckout
    runs-on: self-hosted
    steps:
      - name: Pull Project
        run: |
          cd /home/amitchandi/ && git pull origin main
