name: Publish
on: [push]
jobs:
  # This workflow contains a single job called "SFTP-Deploy-Action"
  CodeCheckout:
    #name: Clone files on amitchandi.com
    runs-on: self-hosted
    steps:
        - uses: actions/checkout@v3
          with:
            # Fetch all history for all tags and branches
            fetch-depth: 0
            # Checkout a specific branch
            ref: main
  PullProject:
    needs: CodeCheckout
    runs-on: self-hosted
    steps:
      - name: Pull Project
        run: |
         rm -f /var/www/deploy/* && git pull origin main && cp ./* /var/www/deploy/
      # Deploy to live folder using deploy.sh
      - name: Deploy to live site
        run: sudo /usr/local/bin/deploy.sh

      # Optional: send Discord notification
      - name: Notify deployment
        run: /usr/local/bin/monit-discord.sh "Website deployed successfully" 
