name: Publish
on: [push]
jobs:
  # This workflow contains a single job called "SFTP-Deploy-Action"
  SFTP-Deploy-Action:
    name: SFTP-Deploy-Action

    # The type of runner that the job will run on 
    # (depends on server but usually this value is works)
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks 
    # that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, 
      # so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:

          # Fetch all history for all tags and branches
          fetch-depth: 0

          # Checkout a specific branch
          ref: main

      - name: Simple SFTP
      # You may pin to the exact commit or the version.
      # uses: Atyn/simple-sftp-action@a684a17fdd2b79d23101d568d9e8b5070f58e685
        uses: Atyn/simple-sftp-action@0.0.2
        with:
          # URL to the SFTP server. Example: sftp://USERNAME:PASSWORD@example.com/remote-directory
          url: sftp://amitchandi:tjVnEn#k!1Oa64m@147.185.242.125
          # The directory that should be uploaded
          #localdir: # optional
          
